// constants.ts
import { Movie } from './types'

export const MOVIE_CATEGORIES = [
    "All",
    "Action",
    "Comedy",
    "Sci-Fi",
    "Drama",
    "Suspense",
    "Ciencia ficción",
    "Fantasía"
  ] as const;

  export const MOVIES: Movie[] = [
    {
      title: "Mad Max: Fury Road",
      image: "/images/mad-max.jfif",
      genre: "Action",
      duration: "2h",
      year: "2015",
      rating: "4.1",
      description: "En un lugar post-apocalíptico, una mujer se rebela contra un gobernante tiránico en busca de su tierra natal con la ayuda de un grupo de mujeres prisioneras, un devoto psicótico y un vagabundo llamado Max.",
    },
    {
      title: "Nacho Libre",
      image: "/images/nacho.jpg",
      genre: "Comedy",
      duration: "1h 32min",
      year: "2006",
      rating: "3.1",
      description: "Tras ser despreciado por los que le rodean durante toda su vida, un monje sigue su sueño y se pone una careta para hacer horas extra como luchador mexicano.",
    },
    {
      title: "Interstellar",
      image: "/images/interestelar.jfif",
      genre: "Sci-Fi",
      duration: "2h 49min",
      year: "2020",
      rating: "4.4",
      description: "Un grupo de exploradores prueban los saltos a través de agujeros de gusano en búsqueda de la sobrevivencia de la humanidad.",
    },
    {
      title: "Red social",
      image: "/images/red-sociall.jfif",
      genre: "Drama",
      duration: "2h",
      year: "2010",
      rating: "3.8",
      description: "Un estudiante de Harvard llamado Mark Zuckerberg crea un sitio de redes sociales conocido como Facebook, pero luego será demandado por dos hermanos que afirman que él robó su idea.",
    },
    {
      title: "El Irlandès",
      image: "/images/elirlandes1.jfif",
      genre: "Suspense",
      duration: "3h 29min",
      year: "2019",
      rating: "4.2",
      description: "Un asesino recuerda haber participado en el asesinato de Jimmy Hoffa.",
    },
    {
      title: "Huye!",
      image: "/images/huye.jfif",
      genre: "Suspense",
      duration: "1h 44min",
      year: "2017",
      rating: "4.0",
      description: "Un joven afroamericano visita a la familia de su novia durante el fin de semana, eventualmente la historia toma un rumbo escalofriante.",
    },
    {
      title: "La llegada",
      image: "/images/lallegada.jfif",
      genre: "Ciencia ficción",
      duration: "1h 56min",
      year: "2016",
      rating: "4.0",
      description: "Después de que doce naves espaciales misteriosas aparecen en todo el mundo, Un lingüista deberá trabajar con los militares para poder comunicarse con las formas de vida extraterrestres.",
    },
    {
      title: "Coco",
      image: "/images/coco.jfif",
      genre: "Fantasía",
      duration: "1h 45min",
      year: "2017",
      rating: "4.5",
      description: "El aspirante a músico Miguel, entra a la Tierra de los Muertos para encontrar a su tatarabuelo, un legendario cantante.",
    },{
      title: "El Padrino",
      image: "/images/padrino.jfif",
      genre: "Drama",
      duration: "2h 55min",
      year: "1972",
      rating: "4.5",
      description: "La historia de la familia Corleone, una familia de la mafia italiana en Nueva York, y su lucha por el poder y la supervivencia.",
    },
    {
      title: "La lista de Schindler",
      image: "/images/schindler.jfif",
      genre: "Drama",
      duration: "3h 15min",
      year: "1993",
      rating: "4.4",
      description: "La historia de Oskar Schindler, un empresario alemán que salva a miles de judíos de la muerte durante el Holocausto.",
    },
    {
      title: "El Señor de los Anillos: La Comunidad del Anillo",
      image: "/images/senor-anillos.jfif",
      genre: "Fantasía",
      duration: "2h 58min",
      year: "2001",
      rating: "4.4",
      description: "La historia de un hobbit llamado Frodo que debe llevar el Anillo Único a la Montaña del Destino para destruirlo y salvar a la Tierra Media del mal.",
    },
    {
      title: "Pulp Fiction",
      image: "/images/pulp-fiction.jfif",
      genre: "Suspense",
      duration: "2h 34min",
      year: "1994",
      rating: "4.3",
      description: "La historia de dos asesinos a sueldo que deben recuperar un valioso objeto para su jefe, mientras que un boxeador debe enfrentar una decisión difícil.",
    },
  ];
  